# Generated by Django 5.2.7 on 2025-12-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tarefa_options_tarefa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
    ]
