# Generated by Django 5.2.7 on 2025-12-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tarefa_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
